### ISSUE TITLE
Failed to upload theme after upgrade @tryghost/admin-api to 1.1.1

### ISSUE THREAD

**Issue by Leo1003** [TryGhost/Ghost-SDK#256]
Welcome to Ghost's GitHub repo! 👋🎉

We use GitHub only for bug reports 🐛

Anything else should be posted to https://forum.ghost.org 👫

🚨For support, help & questions use https://forum.ghost.org/c/help
💡For feature requests & ideas you can post and vote on https://forum.ghost.org/c/Ideas

If your issue is with Ghost CLI, please report it on the CLI repo ➡️ https://github.com/TryGhost/Ghost-CLI/issues/new.

### Issue Summary

I have a auto CD using admin-api to upload themes. After upgrade to 1.1.1, it failed with
```
Error: Must be of FormData or include path
    at Object.upload (/home/leo/projects/libra_casper/node_modules/@tryghost/admin-api/lib/index.js:214:39)
    at main (/home/leo/projects/libra_casper/.github/workflows/deploy-theme.js:12:26)
    at Object.<anonymous> (/home/leo/projects/libra_casper/.github/workflows/deploy-theme.js:20:2)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

I think it is related to #186 . He misunderstood the meaning of the parameter. 
The parameter should able to accept a object containing file path **OR** a file stream of the theme pack.

### Technical details:

* Ghost Version: 3.13.1
* Node Version: 12.16.12

**Comment by ErisDS** [comment]
Thanks for the report - I believe it's fixed now

**Comment by Leo1003** [comment]
Thanks for fixing this so quickly.
