### ISSUE TITLE
content-api, Typescript & Webpack build fails

### ISSUE THREAD

**Issue by daveKoala** [TryGhost/Ghost-SDK#70]
### Issue Summary
Successfully run Typescript compiler and run from complied files
**Error when trying to run with a Webpack build**. The error is:
```
TypeError: r is not a constructor
    at e.getArticleBySlug (/home/david/strataV2/strata-cms.api/dist/bundle.js:1:3078)
  ...........
```
## Technologies
I am using Ghost Content API within a service that is
Node 10.15.2
```
"typescript": "^2.9.2",
"ts-loader": "^5.3.3",
"webpack": "^4.29.6",
 "webpack-cli": "^3.2.3"
```

### To Reproduce with a Express.js TypeScript project
1. npm install @tryghost/content-api
2. A controller with the following method (using your example)
```
import { Request, Response } from "express";
import * as GhostContentAPI from '@tryghost/content-api';

export getPosts = (req: Request, res: Response) => {
const api = new GhostContentAPI({
    url: "http://.............................azure.com",
    key: "a405..................dbb1",
    version: "v2",
  });

api.posts
    .browse({limit: 5, include: 'tags,authors'})
    .then((posts: any) => {

        posts.forEach((post: any) => {
            console.log(post.title);
        });
        res.status(200).json(posts);
    })
    .catch((err: any) => {
        console.error(err);
        res.statusMessage = err.message;
        res.status(404).end();
    });
}
```
Running either:
```
ts-node src/server.ts
```
or
```
tsc
node dist/server.js
```
Works as expected.

Running 
```
webpack -p
```
Complies without errors, starts without issues. Hitting the endpoint that calls the method above results in the error
```
TypeError: r is not a constructor
    at e.getArticleBySlug (/home/david/strataV2/strata-cms.api/dist/bundle.js:1:3078)
    at Layer.handle [as handle_request] (/home/david/strataV2/strata-cms.api/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/david/strataV2/strata-cms.api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/david/strataV2/strata-cms.api/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/david/strataV2/strata-cms.api/node_modules/express/lib/router/layer.js:95:5)
    at /home/david/strataV2/strata-cms.api/node_modules/express/lib/router/index.js:281:22
    at param (/home/david/strataV2/strata-cms.api/node_modules/express/lib/router/index.js:354:14)
    at param (/home/david/strataV2/strata-cms.api/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/david/strataV2/strata-cms.api/node_modules/express/lib/router/index.js:410:3)
    at next (/home/david/strataV2/strata-cms.api/node_modules/express/lib/router/index.js:275:10)

```

If I import GhostContentAPI like
```
import GhostContentAPI from '@tryghost/content-api';
```
results in the following
```
TypeError: content_api_1.default is not a constructor
    at exports.getArticleBySlug (/home/david/strataV2/strata-cms.api/src/controllers/Article.controller.ts:6:15)
    at Layer.handle [as handle_request] (/home/david/strataV2/strata-cms.api/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/david/strataV2/strata-cms.api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/david/strataV2/strata-cms.api/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/david/strataV2/strata-cms.api/node_modules/express/lib/router/layer.js:95:5)
    at /home/david/strataV2/strata-cms.api/node_modules/express/lib/router/index.js:281:22
    at param (/home/david/strataV2/strata-cms.api/node_modules/express/lib/router/index.js:354:14)
    at param (/home/david/strataV2/strata-cms.api/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/david/strataV2/strata-cms.api/node_modules/express/lib/router/index.js:410:3)
    at next (/home/david/strataV2/strata-cms.api/node_modules/express/lib/router/index.js:275:10)
```

## Typescript deceleration file: ghostContent.d.ts
```
declare module '@tryghost/content-api';
```

**Comment by allouis** [comment]
Hey, I tried running your example and Typescript will not compile the code you've posted.

I've replaced it with this and it compiles, and works fine both before and after using webpack.

```
import * as GhostContentAPI from '@tryghost/content-api';

export function getPosts() {
  const api = new GhostContentAPI({
    url: "http://localhost:2368",
    key: "**************************",
    version: "v2",
  });

  api.posts
    .browse({limit: 5, include: 'tags,authors'})
    .then((posts: any) => {

      posts.forEach((post: any) => {
        console.log(post.title);
      });
    })
    .catch((err: any) => {
      console.error(err);
    });
}

getPosts();
```

We'll need some easier to reproduce steps to get this solved!

Out of interest, what is the reason for using webpack on serverside code?

**Comment by kevinansfield** [comment]
@allouis is there anything further to do here or can this be closed?

**Comment by allouis** [comment]
Can't replicate and no activity - closing :)

**Comment by zpydee** [comment]
@daveKoala did you ever resolve your issue? I'm experiencing similar behaviour.
@allouis my need to use webpack is because I'm compiling an angular app for server-side rendering.

**Comment by daveKoala** [comment]
@zpydee I am using the api successfully - I don't remember what i done but if you want me to look let me know and i'll fish the code out

**Comment by NafunaAfrica** [comment]
yes please. I am doing a connection from svelte and I need to know how you overcame that as I still am facing issues

**Comment by jsplate** [comment]
I faced the same problem.

As far as I understand the error is related to the fact that a CommonJS module is not imported in compliance with the es6 module spec because an import can only be a plain object and is not callable.

To avoid this problem in typescript the variable `esModuleInterop` can be set to true in **tsconfig.json** which removes the error.
esModuleInterop generates helper code to avoid this problem.

@allouis maybe you had esModuleInterop already set in your tsconfig.json? Then it is not reproducible.

I am not sure if the problem also exists if plain es6 (without typescript) is used...
